- hosts: web
  become: true
  serial: 1

  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Configure Docker insecure registry for Nexus
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["10.10.2.248:8082"]
          }
        owner: root
        group: root
        mode: "0644"

    - name: Ensure Docker is running
      service:
        name: docker
        state: restarted
        enabled: true