variable "project_name" { type = string }
variable "env" { type = string }
variable "vpc_id" { type = string }
variable "subnet_ids" { type = list(string) }
variable "key_name" { type = string }
variable "target_group_arn" { type = string }
variable "alb_security_group" { type = string }
variable "bastion_security_group" { type = string }
variable "instance_type" { type = string }
variable "desired_capacity" { type = number }
variable "min_size" { type = number }
variable "max_size" { type = number }
variable "ami_id" { type = string}
